### ISSUE TITLE
Approach for running GHA that loads image on job

### ISSUE THREAD

**Issue by Clint-Chester** [CycodeLabs/cimon-action#93]
Hi there, was hoping you had some recommendations on dealing with an approach for GitHub Actions when the job loads in its own image. Example below.

```
jobs:
  deploy:
    name: Run job
    runs-on: ubuntu-latest
    container:
      image: <custom-image>
```
Unfortunately was a generic error of:

![Image](https://github.com/user-attachments/assets/7ffa9c5a-0e2f-411f-b9e9-f83412c80ce3)

Any advice on it would be greatly appreciated, thanks!
